# Generated by Django 3.2.4 on 2021-06-26 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210625_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 26, 13, 17, 45, 585737, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='auction',
            name='updated',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 26, 13, 17, 45, 585737, tzinfo=utc)),
        ),
    ]
