# Generated by Django 3.2.4 on 2021-06-26 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210626_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 13, 19, 23, 161583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 13, 19, 23, 161583, tzinfo=utc)),
        ),
    ]
