# Generated by Django 3.2.4 on 2021-06-26 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210626_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 13, 37, 31, 68068, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 13, 37, 31, 68068, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 13, 37, 31, 68068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 13, 37, 31, 68068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 13, 37, 31, 68068, tzinfo=utc)),
        ),
    ]
