# Generated by Django 3.2.4 on 2021-06-26 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210626_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 18, 19, 24, 970565)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 18, 19, 24, 970565)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 18, 19, 24, 970565)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 18, 19, 24, 986198)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 18, 19, 24, 986198)),
        ),
    ]
