# Generated by Django 3.2.4 on 2021-06-27 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210626_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 48, 31, 551716)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 48, 31, 551716)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 48, 31, 551716)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 48, 31, 561915)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 48, 31, 561915)),
        ),
    ]
